/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin-users'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin/analytics'
import { Route as AdminAuditLogsRouteImport } from './routes/_admin/audit-logs'
import { Route as AdminMonitoringRouteImport } from './routes/_admin/monitoring'
import { Route as AdminProfilRouteImport } from './routes/_admin/profil'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminTenantsIndexRouteImport } from './routes/_admin/tenants/index'
import { Route as AdminTenantsIdRouteImport } from './routes/_admin/tenants/$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/monitoring': typeof AdminMonitoringRoute
  '/profil': typeof AdminProfilRoute
  '/settings': typeof AdminSettingsRoute
  '/tenants/$id': typeof AdminTenantsIdRoute
  '/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/monitoring': typeof AdminMonitoringRoute
  '/profil': typeof AdminProfilRoute
  '/settings': typeof AdminSettingsRoute
  '/': typeof AdminIndexRoute
  '/tenants/$id': typeof AdminTenantsIdRoute
  '/tenants': typeof AdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin-users': typeof AdminAdminUsersRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/monitoring': typeof AdminMonitoringRoute
  '/_admin/profil': typeof AdminProfilRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/tenants/$id': typeof AdminTenantsIdRoute
  '/_admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-users'
    | '/analytics'
    | '/audit-logs'
    | '/monitoring'
    | '/profil'
    | '/settings'
    | '/tenants/$id'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin-users'
    | '/analytics'
    | '/audit-logs'
    | '/monitoring'
    | '/profil'
    | '/settings'
    | '/'
    | '/tenants/$id'
    | '/tenants'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/admin-users'
    | '/_admin/analytics'
    | '/_admin/audit-logs'
    | '/_admin/monitoring'
    | '/_admin/profil'
    | '/_admin/settings'
    | '/_admin/'
    | '/_admin/tenants/$id'
    | '/_admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin-users': {
      id: '/_admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/monitoring': {
      id: '/_admin/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/profil': {
      id: '/_admin/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenants/': {
      id: '/_admin/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenants/$id': {
      id: '/_admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
